name: ci

on:
  schedule:
    - cron: '0 10 * * 0'
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image:  sequring/knife8s
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
